### ISSUE TITLE
Optional capture groups?

### ISSUE THREAD

**Issue by a3nm** [remi-dupre/enum-spanner#6]
Not super important but is it normal that capture groups cannot be optional?

This works:

```
$ echo ab | ./src/main.py --no-debug '(?P<agroup>a)(?P<bgroup>b)'
0: [⊢agroup]a[agroup⊣][⊢bgroup]b[bgroup⊣]
```

But this fails:

```
$ echo ab | ./src/main.py --no-debug '(?P<agroup>a)(?P<bgroup>b)?'
Traceback (most recent call last):
  File "./src/main.py", line 65, in <module>
    for count, match in enumerate(enum_matches(pattern, document)):
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/__init__.py", line 20, in enum_matches
    for mapping in enum_mappings(va, text):
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/explore_dag.py", line 107, in enum_dag_mappings
    jump = Jump(dag)
  File "/home/a3nm/git/enum-spanner/src/benchmark.py", line 44, in wrapper
    ret = function(*args, **kwargs)
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/precompute_dag.py", line 102, in __init__
    self.levelset = LevelSet(dag)
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/precompute_dag.py", line 61, in __init__
    self.__init_levels__()
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/precompute_dag.py", line 85, in __init_levels__
    self.vertex_index[vertex] = len(self.vertices[level])
IndexError: list index out of range
```

In perl, however, it works:

```
$ echo a | perl -p -e 's/^(?P<agroup>a)(?P<bgroup>b)?$/agroup:$+{agroup} bgroup:$+{bgroup}/'
agroup:a bgroup:
$ echo ab | perl -p -e 's/^(?P<agroup>a)(?P<bgroup>b)?$/agroup:$+{agroup} bgroup:$+{bgroup}/'
agroup:a bgroup:b
```

**Comment by a3nm** [comment]
Not quite ;)

```
$ echo ab | ./src/main.py --no-debug '(?P<agroup>a)(?P<bgroup>b*)?' 
Traceback (most recent call last):
  File "./src/main.py", line 87, in <module>
    for count, match in enumerate(enum_matches(pattern, document)):
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/__init__.py", line 20, in enum_matches
    for mapping in enum_mappings(va, text):
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/explore_dag.py", line 119, in enum_dag_mappings
    for Sp, new_gamma in next_level(dag, gamma):
  File "/home/a3nm/git/enum-spanner/src/benchmark.py", line 57, in generator_wrapper
    val = next(ret)
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/explore_dag.py", line 86, in next_level
    gamma2 = follow_epsilons(dag, follow_SpSm(dag, gamma, Sp, Sm))
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/explore_dag.py", line 40, in follow_SpSm
    return [vertex for vertex, ps in path_set.items() if len(ps) == len(Sp)]
  File "/home/a3nm/git/enum-spanner/src/enum_mappings/explore_dag.py", line 40, in <listcomp>
    return [vertex for vertex, ps in path_set.items() if len(ps) == len(Sp)]
TypeError: object of type 'NoneType' has no len()
```

**Comment by a3nm** [comment]
Looks like this latter problem is fixed. :) However there still seems to be a problem:

```
$ echo aa | ./src/main.py -b --no-debug '(?P<agroup>a)?'
0,0 agroup=None,None: aa
1,1 agroup=None,None: aa
0,1 agroup=0,1: [⊢agroup]a[agroup⊣]a
2,2 agroup=None,None: aa
1,2 agroup=1,2: a[⊢agroup]a[agroup⊣]
```

Looks like we're getting duplicate matches, no? Either the group is matched to one of the a's, or it's not matched: why would there be three different ways of not matching it?

**Comment by remi-dupre** [comment]
The reason is it always try to match the "entire" expression. Your example will be rewritten to something like `^.*(?P<match>(?P<agroup>a)?.*)$` before computing anything. It creates a new group **match** which is used to identify where the expression is matched. Here this group matches all empty subwords.

I implemented this behaviour because I think it is closer to the usual regexp semantic where you want to match an expression and you can extract parts of it using groups, but what you except might be more convenient to use.

It is possible to override the main **match** group: `(?P<match>a)?` or to force it to match the whole input : `^.*(?P<agroup>a)?.*$`.

PS: '^' and '$' symbols are not implemented (yet?) and only work when placed at the begining and end of the expression thanks to a dirty hack.

unrelated PS: the very last commit breaks the memory saving behaviour
